# Generated by Django 3.2.4 on 2021-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='specialist',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
