# Generated by Django 3.2.4 on 2021-10-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211016_1759'),
        ('users', '0003_auto_20211016_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='specialist_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speicialists', to='services.service'),
        ),
    ]
