# Generated by Django 3.2.4 on 2021-10-16 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_staffschedule_specialist_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
