# Generated by Django 3.2.4 on 2021-10-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_at',
            new_name='appointment_on',
        ),
    ]
